# Generated by Django 6.0.7 on 2026-09-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevens', '0042_vgnotaentrega_estado_anulada'),
        ('sevens', '0046_vgconciliacionbancaria'),
    ]

    operations = [
    ]
