# Generated by Django 6.0.7 on 2026-09-27 18:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevens', '0063_vgcompra_moneda_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGGrupoOpcionRacionPorTamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo_peso_gramos', models.PositiveIntegerField(help_text='Peso del plato principal, en gramos, al que aplica esta fila (ej: 500).')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cuánto descontar de este producto en este tramo. Si el producto tiene venta_por_peso activo son GRAMOS (ej: 120.00); si no, son UNIDADES directas (ej: 3.00 patacones).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raciones_por_tamano', to='sevens.vggrupoopcionproducto')),
                ('producto', models.ForeignKey(help_text='Producto acompañante (de la categoría dinámica del grupo) al que aplica esta fila.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sevens.vgproducto')),
            ],
            options={
                'verbose_name': 'Ración por tamaño',
                'verbose_name_plural': 'Raciones por tamaño',
                'db_table': 'vg_grupo_opcion_raciones_por_tamano',
                'ordering': ['grupo_id', 'producto_id', 'tramo_peso_gramos'],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'producto', 'tramo_peso_gramos'), name='racion_por_tamano_unica')],
            },
        ),
    ]
