# Generated by Django 6.0.7 on 2026-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevens', '0067_alter_vgingresoextra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='numero_cobro',
            field=models.PositiveIntegerField(blank=True, help_text="Correlativo de la 'nota de cobro' (serie NOTA_COBRO). Visible como COB-000001.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='saldo_posterior',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Saldo pendiente de la nota (USD) justo después de este abono.', max_digits=14, null=True),
        ),
    ]
